import zaraImage from '@assets/images/png/shopsImages/zara.png';
import mediaMarketImage from '@assets/images/png/shopsImages/mediaMarkt.png';
import notinoImage from '@assets/images/png/shopsImages/notino.png';
import answerImage from '@assets/images/png/shopsImages/answer.png';
import zalandoImage from '@assets/images/png/shopsImages/zalando.png';
import newBalanceImage from '@assets/images/png/shopsImages/newBalance.png';
import allegroImage from '@assets/images/png/shopsImages/allegro.png';
import headPhones from '@assets/images/png/goodsImages/headPhones.png';
import table from '@assets/images/png/goodsImages/table.png';
import jacket from '@assets/images/png/goodsImages/jacket.png';
import laptop from '@assets/images/png/goodsImages/laptop.png';
import sneakerYeezy from '@assets/images/png/goodsImages/sneakerYeezy.png';
import sneakerZigKinetica from '@assets/images/png/goodsImages/sneakerZigKinetica.png';
import sneakerNewBalance from '@assets/images/png/goodsImages/sneakerNewBalance.png';
import sneakerAirJordanMid from '@assets/images/png/goodsImages/sneakerAirJordanMid.png';
import playStation from '@assets/images/png/goodsImages/playStation.png';
import sneakerAdidasForum from '@assets/images/png/goodsImages/sneakerAdidasForum.png';
import perfume from '@assets/images/png/goodsImages/parfume.png';
import washingMachine from '@assets/images/png/goodsImages/washingMachine.png';
import television from '@assets/images/png/goodsImages/television.png';
import sneakerAirJordan from '@assets/images/png/goodsImages/sneakerAirJordan.png';
import earPhones from '@assets/images/png/goodsImages/earPhones.png';
import wheel from '@assets/images/png/goodsImages/wheel.png';

export const SHOPS = [
  {
    id: 1,
    category: 'одежда, обувь, аксессуары',
    image: zaraImage,
    link: 'https://www.zara.com/pl/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 2,
    category: 'техника',
    image: mediaMarketImage,
    link: 'https://mediamarkt.pl/',
    description: 'Магазин техники',
  },
  {
    id: 3,
    category: 'парфюмерия',
    image: notinoImage,
    link: 'https://www.notino.pl/',
    description: 'Магазин парфюмерии',
  },
  {
    id: 4,
    category: 'кроссовки',
    image: answerImage,
    link: 'https://answear.com/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 5,
    category: 'одежда, обувь, аксессуары',
    image: zalandoImage,
    link: 'https://www.zalando.pl/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 6,
    category: 'кроссовки',
    image: newBalanceImage,
    link: 'https://nbsklep.pl/',
    description: 'Официальный магазин New Balance',
  },
  {
    id: 7,
    category: 'прочие товары',
    image: allegroImage,
    link: 'https://allegro.pl/',
    description: 'Площадка с магазинами где можно найти всё',
  },
  {
    id: 8,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://www.adidas.pl/',
    description: 'Официальный магазин Adidas',
  },
  {
    id: 9,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://www.reebok.pl/',
    description: 'Официальный магазин Reebok',
  },
  {
    id: 10,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://eastendshop.com/pl',
    description: 'Официальный магазин Eastend',
  },
  {
    id: 11,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://sklepmartens.pl/',
    description: 'Официальный магазин Dr.Martens',
  },
  {
    id: 12,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://e-timberland.pl/',
    description: 'Официальный магазин Timberland',
  },
  {
    id: 13,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://www.symbiosis.com.pl/',
    description: 'Symbiosis - интернет-магазин, предлагающий обувь и аксессуары высочайшего качества',
  },
  {
    id: 14,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://www.ataf.pl/',
    description: 'Магазин кроссовок',
  },
  {
    id: 15,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://www.eobuwie.com.pl/',
    description: 'Магазин кроссовок',
  },
  {
    id: 16,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://50style.pl/',
    description: 'Магазин кроссовок',
  },
  {
    id: 17,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://worldbox.pl/',
    description: 'Магазин кроссовок',
  },
  {
    id: 18,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://warsawsneakerstore.com/',
    description: 'Магазин кроссовок',
  },
  {
    id: 19,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://skstore.pl/',
    description: 'Магазин обуви и одежды для баскетбола',
  },
  {
    id: 20,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://sneakerstudio.pl/',
    description: 'Магазин кроссовок',
  },
  {
    id: 21,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://sneakerpeeker.pl/',
    description: 'Магазин кроссовок',
  },
  {
    id: 22,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://runcolors.pl/',
    description: 'Магазин кроссовок',
  },
  {
    id: 23,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://basketzone.pl/',
    description: 'Магазин кроссовок',
  },
  {
    id: 24,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://sneakershop.pl/',
    description: 'Магазин кроссовок',
  },
  {
    id: 25,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://sklep.sizeer.com/',
    description: 'Магазин кроссовок',
  },
  {
    id: 26,
    category: 'кроссовки',
    image: zaraImage,
    link: 'https://sklepkoszykarza.pl/',
    description: 'Магазин кроссовок',
  },
  {
    id: 27,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://answear.com/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 28,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://gomez.pl/',
    description: 'Одежда и обувь премиум',
  },
  {
    id: 29,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://eastendshop.com/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 30,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://supersklep.pl/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 31,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://modivo.pl/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 32,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://www.ataf.pl/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 33,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://50style.pl/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 34,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://royal-shop.pl/',
    description: 'Одежда и обувь премиум',
  },
  {
    id: 35,
    category: 'одежда, обувь, аксессуары',
    image: zaraImage,
    link: 'https://www.zara.com/pl/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 36,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://www.uterque.com/pl/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 37,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://www.vitkac.com/pl/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 38,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://www.massimodutti.com/pl/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 39,
    category: 'одежда, обувь, аксессуары',
    image: answerImage,
    link: 'https://streetsupply.pl/',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 40,
    category: 'спортивная одежда',
    image: zaraImage,
    link: 'https://www.adidas.pl/',
    description: 'Официальный магазин Adidas',
  },
  {
    id: 41,
    category: 'спортивная одежда',
    image: zaraImage,
    link: 'https://www.reebok.pl/',
    description: 'Официальный магазин Reebok',
  },
  {
    id: 42,
    category: 'спортивная одежда',
    image: newBalanceImage,
    link: 'https://nbsklep.pl/',
    description: 'Официальный магазин New Balance',
  },
  {
    id: 43,
    category: 'спортивная одежда',
    image: newBalanceImage,
    link: 'https://www.mantoshop.pl/',
    description: 'официальный магазин Manto',
  },
  {
    id: 44,
    category: 'спортивная одежда',
    image: newBalanceImage,
    link: 'https://strefatenisa.com.pl/',
    description: 'Магазин одежды, обуви и аксессуаров для тенниса',
  },
  {
    id: 45,
    category: 'спортивная одежда',
    image: newBalanceImage,
    link: 'https://www.r-gol.com/',
    description: 'Магазин одежды, обуви и аксессуаров для футбола',
  },
  {
    id: 46,
    category: 'спортивная одежда',
    image: newBalanceImage,
    link: 'https://11teamsports.pl/',
    description: 'Магазин одежды, обуви и аксессуаров для футбола',
  },
  {
    id: 47,
    category: 'спортивная одежда',
    image: newBalanceImage,
    link: 'https://skstore.pl/',
    description: 'Магазин обуви и одежды для баскетбола',
  },
  {
    id: 48,
    category: 'спортивная одежда',
    image: newBalanceImage,
    link: 'https://basketzone.pl/',
    description: 'магазин обуви и одежды для баскетбола',
  },
  {
    id: 49,
    category: 'спортивная одежда',
    image: newBalanceImage,
    link: 'https://50style.pl/',
    description: 'Магазин спортивной одежды',
  },
  {
    id: 50,
    category: 'спортивная одежда',
    image: newBalanceImage,
    link: 'https://www.active.sklep.pl/',
    description: 'Магазин спортивной одежды',
  },
  {
    id: 51,
    category: 'спортивная одежда',
    image: newBalanceImage,
    link: 'https://sportroom.pl/',
    description: 'Магазин спортивной одежды',
  },
  {
    id: 52,
    category: 'спортивная одежда',
    image: newBalanceImage,
    link: 'http://www.sportjam.pl/',
    description: 'Магазин спортивной одежды',
  },
  {
    id: 53,
    category: 'парфюмерия',
    image: notinoImage,
    link: 'https://www.sephora.pl/',
    description: 'Магазин парфюмерии',
  },
  {
    id: 54,
    category: 'парфюмерия',
    image: notinoImage,
    link: 'https://www.douglas.pl/',
    description: 'Магазин парфюмерии',
  },
  {
    id: 55,
    category: 'парфюмерия',
    image: notinoImage,
    link: 'https://www.hairstore.pl/',
    description: 'Магазин парфюмерии',
  },
  {
    id: 56,
    category: 'парфюмерия',
    image: notinoImage,
    link: 'https://www.superpharm.pl/',
    description: 'Магазин парфюмерии',
  },
  {
    id: 57,
    category: 'парфюмерия',
    image: notinoImage,
    link: 'https://www.topestetic.pl/',
    description: 'Магазин парфюмерии',
  },
  {
    id: 58,
    category: 'парфюмерия',
    image: notinoImage,
    link: 'https://www.dolce.pl/',
    description: 'Магазин парфюмерии',
  },
  {
    id: 59,
    category: 'парфюмерия',
    image: notinoImage,
    link: 'https://estyl.pl/',
    description: 'Магазин парфюмерии',
  },
  {
    id: 60,
    category: 'часы',
    image: notinoImage,
    link: 'https://www.e-zegarki.pl/',
    description: 'Магазин часов',
  },
  {
    id: 61,
    category: 'часы',
    image: notinoImage,
    link: 'https://zegarownia.pl/',
    description: 'Магазин часов',
  },
  {
    id: 62,
    category: 'часы',
    image: notinoImage,
    link: 'https://montres.pl/',
    description: 'Магазин часов',
  },
  {
    id: 63,
    category: 'часы',
    image: notinoImage,
    link: 'https://happytime.com.pl/',
    description: 'Магазин часов',
  },
  {
    id: 64,
    category: 'часы',
    image: notinoImage,
    link: 'https://www.zegarek.net/',
    description: 'Магазин часов',
  },
  {
    id: 65,
    category: 'строительство, мебель',
    image: notinoImage,
    link: 'https://leroymerlin.pl',
    description: 'Строительный и мебельный магазин',
  },
  {
    id: 66,
    category: 'строительство, мебель',
    image: notinoImage,
    link: 'https://bricoman.pl',
    description: 'Строительный и мебельный магазин',
  },
  {
    id: 67,
    category: 'строительство, мебель',
    image: notinoImage,
    link: 'https://euroogrod.com.pl',
    description: 'Строительный и мебельный магазин',
  },
  {
    id: 68,
    category: 'сантехника',
    image: notinoImage,
    link: 'https://www.sklepbaterie.pl',
    description: 'Магазин сантехники',
  },
  {
    id: 69,
    category: 'сантехника',
    image: notinoImage,
    link: 'https://www.zielonalazienka.pl',
    description: 'Магазин сантехники',
  },
  {
    id: 70,
    category: 'сантехника',
    image: notinoImage,
    link: 'https://elazienki.pl',
    description: 'Магазин сантехники',
  },
  {
    id: 71,
    category: 'сантехника',
    image: notinoImage,
    link: 'https://lazienkarium.pl',
    description: 'Магазин сантехники',
  },
  {
    id: 72,
    category: 'автозапчасти',
    image: allegroImage,
    link: 'https://allegro.pl',
    description: 'Магазин автозапчастей',
  },
  {
    id: 73,
    category: 'автозапчасти',
    image: allegroImage,
    link: 'https://www.iparts.pl',
    description: 'Магазин автозапчастей',
  },
  {
    id: 74,
    category: 'автозапчасти',
    image: allegroImage,
    link: 'https://motostacja.com',
    description: 'Магазин автозапчастей',
  },
  {
    id: 75,
    category: 'техника',
    image: mediaMarketImage,
    link: 'https://www.thomann.de/pl',
    description: 'Магазин техники',
  },
  {
    id: 76,
    category: 'техника',
    image: mediaMarketImage,
    link: 'https://www.x-kom.pl',
    description: 'Магазин техники',
  },
  {
    id: 77,
    category: 'техника',
    image: mediaMarketImage,
    link: 'https://www.avans.pl',
    description: 'Магазин техники',
  },
  {
    id: 78,
    category: 'техника',
    image: mediaMarketImage,
    link: 'https://www.mall.pl',
    description: 'Магазин техники',
  },
  {
    id: 79,
    category: 'техника',
    image: mediaMarketImage,
    link: 'https://www.neo24.pl',
    description: 'Магазин техники',
  },
  {
    id: 80,
    category: 'техника',
    image: mediaMarketImage,
    link: 'https://www.euro.com.pl',
    description: 'Магазин техники',
  },
  {
    id: 81,
    category: 'одежда, обувь, аксессуары',
    image: newBalanceImage,
    link: 'https://www.nike.com/pl/w',
    description: 'Одежда, обувь и аксессуары',
  },
  {
    id: 82,
    category: 'строительство, мебель',
    image: notinoImage,
    link: 'https://www.ikea.com/pl/pl/',
    description: 'Строительный и мебельный магазин',
  },
];

export const GOODS = [
  {
    id: 'Airpods Max',
    title: 'Airpods Max',
    economy: 240,
    image: headPhones,
  },
  {
    id: 'IKEA HEMNES',
    title: 'IKEA HEMNES',
    economy: 50,
    image: table,
  },
  {
    id: 'Куртка Zara',
    title: 'Куртка Zara',
    economy: 50,
    image: jacket,
  },
  {
    id: 'MacBook Pro 16 M2 Pro',
    title: 'MacBook Pro 16 M2 Pro',
    economy: 350,
    image: laptop,
  },
  {
    id: 'Yeezy 500 Blush',
    title: 'Yeezy 500 Blush',
    economy: 120,
    image: sneakerYeezy,
  },
  {
    id: 'Zig Kinetica 2.5 Edge',
    title: 'Zig Kinetica 2.5 Edge',
    economy: 50,
    image: sneakerZigKinetica,
  },
  {
    id: 'New Balance U327WED',
    title: 'New Balance U327WED',
    economy: 80,
    image: sneakerNewBalance,
  },
  {
    id: 'Air Jordan 1 Mid',
    title: 'Air Jordan 1 Mid',
    economy: 50,
    image: sneakerAirJordanMid,
  },
  {
    id: 'Sony Playstation 5',
    title: 'Sony Playstation 5',
    economy: 240,
    image: playStation,
  },
  {
    id: 'Adidas Forum Low',
    title: 'Adidas Forum Low',
    economy: 50,
    image: sneakerAdidasForum,
  },
  {
    id: 'Giorgio Armani Si',
    title: 'Giorgio Armani Si',
    economy: 240,
    image: perfume,
  },
  {
    id: 'SAMSUNG WW90T634DLH',
    title: 'SAMSUNG WW90T634DLH',
    economy: 150,
    image: washingMachine,
  },
  {
    id: 'LG OLED55C21LA',
    title: 'LG OLED55C21LA',
    economy: 320,
    image: television,
  },
  {
    id: 'Nike AirJordan 1',
    title: 'Nike AirJordan 1',
    economy: 50,
    image: sneakerAirJordan,
  },
  {
    id: 'BEATS Studio Buds',
    title: 'BEATS Studio Buds',
    economy: 56,
    image: earPhones,
  },
  {
    id: 'Michelin Primacy 4',
    title: 'Michelin Primacy 4',
    economy: 250,
    image: wheel,
  },
];

export const FEEDBACKS_DATA = [
  {
    id: 1,
    video: '',
    title: 'Дима, Минск',
  },
  {
    id: 5,
    video: '',
    title: 'Вика, Москва',
  },
  {
    id: 9,
    video: '',
    title: 'Гриша, Орша',
  },
  {
    id: 12,
    video: '',
    title: 'Мага, Махачкала',
  },
];

export const CATEGORIES = [
  {
    id: 1,
    category: 'все магазины',
  },
  {
    id: 2,
    category: 'кроссовки',
  },
  {
    id: 3,
    category: 'одежда, обувь, аксессуары',
  },
  {
    id: 4,
    category: 'спортивная одежда',
  },
  {
    id: 5,
    category: 'парфюмерия',
  },
  {
    id: 6,
    category: 'часы',
  },
  {
    id: 7,
    category: 'строительство, мебель',
  },
  {
    id: 8,
    category: 'сантехника',
  },
  {
    id: 9,
    category: 'автозапчасти',
  },
  {
    id: 10,
    category: 'техника',
  },
  {
    id: 11,
    category: 'прочие товары',
  },
];
